all: $(imgPath)
	g++ -w the3.cpp -o fat32-shell && ./fat32-shell $(imgPath)
debug: $(imgPath)
	g++ -g -w the3.cpp -o fat32-shell && gdb --args fat32-shell $(imgPath)
check: $(imgPath)
	fsck.vfat -vn $(imgPath)
unmount: $(rootDir)
	fusermount -u $(rootDir) && rm -rf $(rootDir)
mount: $(rootDir) $(imgPath)
	mkdir $(rootDir) && chmod 700 $(rootDir) && fusefat -o rw+ -o umask=770 $(imgPath) $(rootDir)
